CREATE TABLE Brands
(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
BRAND VARCHAR(100));

CREATE TABLE Types
(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TYPE VARCHAR(100));

CREATE TABLE Features
(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
FEATURE VARCHAR(100));

CREATE TABLE Products
(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TYPE_ID BIGINT REFERENCES Types(ID),
BRAND_ID BIGINT REFERENCES Brands(ID),
TITLE VARCHAR(100),
COUNT BIGINT,
PRICE BIGINT);

CREATE TABLE Product_Features
(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
PRODUCT_ID BIGINT REFERENCES Products(id),
FEATURE_ID BIGINT REFERENCES Features(id),
VALUE VARCHAR(100));