CREATE TABLE Brands
(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TITLE VARCHAR(100) NOT NULL);

CREATE TABLE Types
(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TYPE VARCHAR(100) NOT NULL);

CREATE TABLE Features
(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
FEATURE VARCHAR(100) NOT NULL);

CREATE TABLE Products
(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
TYPE_ID VARCHAR(100) NOT NULL REFERENCES Types(id),
BRAND_ID VARCHAR(100) NOT NULL REFERENCES Brands(id),
TITLE VARCHAR(100) NOT NULL,
COUNT BIGINT NOT NULL,
PRICE BIGINT NOT NULL);

CREATE TABLE Product_Features
(PRODUCT_ID BIGINT NOT NULL REFERENCES Products(id),
FEATURE_ID BIGINT NOT NULL REFERENCES Features(id),
VALUE VARCHAR(100) NOT NULL);